name: better_proto_mapper_example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  better_proto_annotations:
    path: ../better_proto_annotations
  protobuf: ^3.1.0

dev_dependencies:
  better_proto_generator:
    path: ../better_proto_generator
  build_runner: ^2.4.7
  lints: ^3.0.0
  test: ^1.24.0
