# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:

  protoBuilder:
    import: "package:better_proto_generator/better_proto_generator.dart"
    builder_factories: ["protoBuilder", "protoMapperBuilder"]
    build_extensions: { "$lib$": [".tproto"], ".dart": ["proto_mapper.g.part"] }
    build_to: cache
    auto_apply: dependents
    runs_before: [":protoFromCache"]
    applies_builders: [":protoFromCache"]

  protoFromCache:
    import: "package:better_proto_generator/better_proto_generator.dart"
    builder_factories: ["protoFromCache"]
    build_extensions: {".tproto": [".proto"]}
    build_to: source
    required_inputs: [".tproto"]
    runs_before: [":protocRunner"]
    applies_builders: [":protocRunner"]

  protocRunner:
    import: "package:better_proto_generator/better_proto_generator.dart"
    builder_factories: ["protocRunner"]
    build_extensions: { "$lib$": ["*"] }
    build_to: source
    required_inputs: [".proto"]
    auto_apply: dependents
    runs_before: ["source_gen:combining_builder"]
    applies_builders: ["source_gen:combining_builder"]
