# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:

  protoBuilder:
    import: "package:better_proto_generator/better_proto_generator.dart"
    builder_factories: ['protoBuilder', 'protoMapperBuilder']
    build_extensions:
      $lib$:
        - .tproto
      .dart:
        - proto_map.g.part
    build_to: cache
    auto_apply: root_package
    applies_builders: ["source_gen:combining_builder", "better_proto_generator:protoFromCache"]


  protoFromCache:
    import: "package:better_proto_generator/better_proto_generator.dart"
    builder_factories: ['protoFromCache']
    build_extensions: {".tproto": [".proto"]}
    required_inputs: [".tproto"]
    build_to: source
    auto_apply: none
